version: "3"

services:
  app:
    build: .
    command: yarn dev
    ports:
      - "3333:3333"
    environment:
      - DB_HOST=database
      - RD_HOST=redis
    volumes:
      - ".:/usr/app"

  database:
    image: mongo

  redis:
    image: redis
